server:
  port: 10080
spring:
  application:
    name: gateway-api
zuul:
  routes:
    users:
      path: /item-api/**
      #url: http://127.0.0.1:7080
      serviceId: item-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:10000/eureka/
  instance:
    prefer-ip-address: true