server:
  port: 10002
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jason009/cloud.git
          search-paths: config-server